# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-20 03:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nusxchange', '0003_auto_20170720_0301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nusxchange.School'),
        ),
    ]
