# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-20 03:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nusxchange', '0004_auto_20170720_0315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='school',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'School of Computing'), (2, 'Faculty of Social Science'), (3, 'Faculty of Science'), (4, 'Business and '), (5, 'Dentistry'), (6, 'Design & Environment'), (7, 'Duke-NUS'), (8, 'Engineering'), (9, 'Law'), (10, 'Medicine'), (11, 'Music'), (12, 'Public Health'), (13, 'Public Policy'), (3, 'Science'), (14, 'Yale-NUS')], null=True),
        ),
        migrations.DeleteModel(
            name='School',
        ),
    ]
