# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-20 04:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nusxchange', '0005_auto_20170720_0342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='location',
        ),
        migrations.AddField(
            model_name='profile',
            name='accomodation',
            field=models.CharField(default='OT', max_length=2),
        ),
        migrations.AddField(
            model_name='profile',
            name='age',
            field=models.CharField(default=18, max_length=3),
        ),
        migrations.AddField(
            model_name='profile',
            name='facebook_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='interest',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='profile',
            name='major',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='profile',
            name='matric_num',
            field=models.CharField(default='A0000000Z', max_length=9),
        ),
        migrations.AddField(
            model_name='profile',
            name='nationality',
            field=models.CharField(default='OT', max_length=2),
        ),
        migrations.AddField(
            model_name='profile',
            name='title',
            field=models.CharField(choices=[('MR', 'Mr.'), ('MRS', 'Mrs.'), ('MS', 'Ms.')], default='MR', max_length=3),
        ),
        migrations.AlterField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='school',
            field=models.PositiveSmallIntegerField(choices=[(1, 'School of Computing'), (2, 'Faculty of Social Science'), (3, 'Faculty of Science'), (4, 'Business and '), (5, 'Dentistry'), (6, 'Design & Environment'), (7, 'Duke-NUS'), (8, 'Engineering'), (9, 'Law'), (10, 'Medicine'), (11, 'Music'), (12, 'Public Health'), (13, 'Public Policy'), (3, 'Science'), (14, 'Yale-NUS')], default=2),
        ),
    ]
