# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-20 07:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nusxchange', '0006_auto_20170720_0447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='nationality',
            field=models.CharField(default='Others', max_length=300),
        ),
    ]
