# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-20 07:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nusxchange', '0007_auto_20170720_0718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='accomodation',
            field=models.CharField(choices=[('TH', 'Temasek Hall'), ('EH', 'Eusoff Hall'), ('CC', 'Cinnamon College'), ('TC', 'Tembusu College'), ('OC', 'Off-Campus')], default='OC', max_length=2),
        ),
        migrations.AlterField(
            model_name='profile',
            name='facebook_url',
            field=models.URLField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nationality',
            field=models.CharField(choices=[('CN', 'China'), ('SG', 'Singapore'), ('OT', 'Others')], default='OT', max_length=2),
        ),
    ]
