# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-20 13:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nusxchange', '0010_auto_20170720_0818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='facebook_url',
            field=models.URLField(blank=True),
        ),
    ]
