# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-22 12:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nusxchange', '0014_auto_20170722_0701'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_picture'),
        ),
    ]
