# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-22 13:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nusxchange', '0015_profile_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profile_management/media/profile_picture/no-img.jpg', null=True, upload_to='profile_management/media/profile_picture'),
        ),
    ]
