# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-22 14:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nusxchange', '0018_auto_20170722_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pu',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
